region program ".program" () {
    var globalval:u32:(align(4));
    var foo1:any:(func,align(4));
    region func foo1 () {
        var stackvar:u64:(align(8));
        stpr $2:u64 = 1:u64;
        stpr $3:u64 = 2:u64;
        stpr $4:u64 = 3:u64;
        stpr $5:*<1> = 4:u64;
        st:u64 stackvar = //The stmt should be removed by DCE.
            $5:*<1>;
        st:u64 stackvar = //can not remove
            $2:u64;
        st:u32 stackvar = //can not remove
            $3:u64;
        st:u8 stackvar = //can not remove
            $4:u64;
        stpr $1:u64 =
            ld:u64 stackvar;
        stpr $5:*<1> =
            lda globalval;
        ist:u64 =
            $5:*<1>,
            $1:u64;
        return ;
    };
}
