region program ".program" () {
    var g:i32:(align(4));
    var s72:*<4>:(func,align(4));
    region func s72 () {
        var rc:i32:(align(4));
        var k:i32:(align(4));
        truebr (
            eq:bool
                ld:i32 k, 0:i32), "_GR__$L1";
        st:i32 g = 7:i32;
        label "_GR__$L1";
        stpr $4:i32 =
            ld:i32 k;
        st:i32 k =
            add:i32
                ld:i32 k, 1:i32;
        truebr (
            eq:bool
                $4:i32, 5:i32), "_GR__$L2";
        label "_GR__$L7";
        stpr $5:bool = 1:bool;
        goto "_GR__$L5";
        label "_GR__$L2";
        stpr $6:i32 =
            ld:i32 k;
        st:i32 k =
            sub:i32
                ld:i32 k, 1:i32;
        truebr (
            eq:bool
                $6:i32, 6:i32), "_GR__$L4";
        label "_GR__$L8";
        stpr $7:bool = 1:bool;
        goto "_GR__$L5";
        label "_GR__$L4";
        stpr $8:bool = 0:bool;
        label "_GR__$L5";
        phi $9:bool = (1:bool,"_GR__$L7"),(1:bool,"_GR__$L8"),(0:bool,"_GR__$L4");
        phi $10:i32 = (
            $2:i32,"_GR__$L7"),(
            $6:i32,"_GR__$L8"),(
            $6:i32,"_GR__$L4");
        falsebr (
            lor:bool
                $9:bool,
                ne:bool
                    ld:i32 k, 5:i32), "_GR__$L6";
        st:i32 g = 8:i32;
        label "_GR__$L6";
        return
            ld:i32 rc;
    };
}
