region program ".program" () {
    var printf:*<4>:(func,align(4));
    var g:i32:(align(4));
    var s85:*<4>:(func,align(4));
    var type:mc<8>:(private,array,align(4));
    var "#DedicatedStringVar":str:(unallocable,align(4),string("DedicatedVarBeRegardedAsString"));
    var _const_string_1:str:(align(4),string("float"));
    var _const_string_2:str:(align(4),string("double"));
    var _const_string_3:str:(align(4),string("%s%d"));
    region func s85 () {
        var diff:mc<28>:(array,align(4));
        var j:i32:(align(4));
        var s3:mc<4>:(align(4));
        var twobit:i32:(align(4));
        var threebit:i32:(align(4));
        label "_GR__$L3";
        starray:*<1>:0:(dim[2]) =
            lda type, (0:i32),
            lda _const_string_1;
        starray:*<1>:0:(dim[2]) =
            lda type, (1:i32),
            lda _const_string_2;
        st:i32 j = 0:i32;
        label "_GR__$L1";
        phi $3:i32 = (
            $2:i32,"_GR__$L3"),(0:i32,"_GR__$L4");
        phi $5:i32 = (
            $1:i32,"_GR__$L3"),(
            $6:i32,"_GR__$L4");
        falsebr (
            lt:bool 0:i32, 5:i32), "_GR__$L2";
        call:(use(
            ild:any 0:any)) $6:i32 = printf(
            lda _const_string_3,
            array:*<1>:0:(dim[2])
                lda type, (0:i32),
            array:i32:0:(dim[7])
                lda diff, (0:i32));
        label "_GR__$L4";
        stpr $4:i32 = 0:i32;
        st:i32 j = 1:i32;
        goto "_GR__$L1";
        label "_GR__$L2";
        st:i32:4 s3 = 7:i32;
        st:i32 s3 = 7:i32;
        st:i32:4 s3 = 7:i32;
        return 0:i32;
    };
}
