region program x() {
region func intrapred (undefined,var img:*<1024>:(align(4))) {
    var i:i32:(align(4));
    var j:i32:(align(4));
    var PredPel:mc<52>:(array,align(4));
    falsebr (
        eq:bool
            ld:i32 i, 4:i32), "_GR__$L1";
    stpr $1:u32 =
        mul:u32 9:i32, 4:u32;
    stpr $2:*<4> =
        add:*<4>
            lda PredPel,
            $1:u32;
    stpr $3:i32 =
        ild:i32
            $2:*<4>;
    stpr $4:u32 =
        mul:u32
            ld:i32 i, 16:u32;
    stpr $5:u32 =
        add:u32
            ld:i32 j,
            $4:u32;
    stpr $6:u32 =
        mul:u32
            $5:u32, 4:u32;
    ist:i32 =
        add:*<4>
            ld:*<1024> img,
            $6:u32,
        mul:i32
            $3:i32, 2:i32;
    stpr $7:u32 =
        mul:u32 9:i32, 4:u32;
    stpr $8:*<4> =
        add:*<4>
            lda PredPel,
            $7:u32;
    stpr $9:i32 =
        ild:i32
            $8:*<4>;
    stpr $10:u32 =
        mul:u32
            ld:i32 i, 16:u32;
    stpr $11:u32 =
        add:u32
            ld:i32 j,
            $10:u32;
    stpr $12:u32 =
        mul:u32
            $11:u32, 4:u32;
    ist:i32 =
        add:*<4>
            ld:*<1024> img,
            $12:u32,
        mul:i32
            $9:i32, 2:i32;
    label "_GR__$L1";
    return ;
}
}
