region program ".program" () {
    var a:u8:(align(4));
    var b::(align(4));
    var c:i16:(func_decl,align(4));
    var d:i16:(func_decl,align(4));
    region func foo (undefined,var in_key:*<1>:(align(4)),var n_bytes:u32:(align(4)),var f:i32:(align(4)),var cx:*<524>:(align(4))) {
        if (eq ld a, ld d) {
            stpr $3 = 1;
            stpr $4 = 1:bool;
        }
        st b = $3;
        do {
            stpr $5 = ld b;
        } while (lt ld c, ld a);
        return $4;
    };
}
