region program ".program" () {
    var a:f32:(align(4));
    var main:u32:(func, readonly, align(4));
    region func main () {
        var rawdata:u32:(func, readonly, align(4));
        var bar:u32:(func, readonly, align(4));
        st a = 0xffffFFFFF;
        region inner bar () {
            var boom:u32:(readonly, align(4));
            var pad:i32:(align(4));
            st pad = ld boom;
        };
        region blackbox rawdata() {
            var bindata:i32:(align(4), byte(1,2,3,4), volatile);
            var strdata:str:(align(4), string("hello"), volatile);
        };
        call:(readonly) main(id rawdata, ld:*<1> bar, ld:*<1> main, 0x10, 0x20, "world");
        return 0;
    };
}
