region program ".program" () {
    var sleep:*<4>:(func_decl,align(4));
    var printf:*<4>:(func_decl,align(4));
    var perror:*<4>:(func_decl,align(4));
    var pthread_create:*<4>:(func_decl,align(4));
    var vvv:i32:(private,align(4));
    var thread1:*<4>:(func_decl,align(4));
    var main:*<4>:(func_decl,align(4));
    var "#DedicatedStringVar":str:(unallocable,align(4),string("DedicatedVarBeRegardedAsString"));
    var _const_string_1:str:(align(4),string("enter
    "));
    var _const_string_2:str:(align(4),string("thread"));
    region func main () {
        var t:mc<4>:(align(4));
        var re:i32:(align(4));
        call:(use(
            ild:any 0:any)) $3:i32 = pthread_create(
            lda t,0:i32,
            lda thread1,0:i32);
        label "_GR__$L4";
        st:i32 re = 
            $3:i32;
        falsebr (
            lt:bool 
                ld:i32 re, 0:i32), "_GR__$L1";
        label "_GR__$L5";
        call:(use(
            ild:any 0:any)) $4:i32 = perror(
            lda _const_string_2);
        label "_GR__$L1";
        phi $5:i32 = (
            $2:i32,"_GR__$L4"),(
            $4:i32,"_GR__$L5"),(
            $5:i32,"_GR__$L1");
        truebr (
            gt:bool 
                ld:i32 vvv, 0:i32), "_GR__$L1";
        return 0:i32;
    };
}
