region program ".program" () {
    var load_elim3:any:(func,align(4));
    region func load_elim3 () {
        var d:i32:(align(4));
        var i:i32:(align(4));
        var x:mc<80>:(array,align(4));
        label "_GR__$L3";
        st:i32 d = 1:i32;
        stpr $16:i32 = ld:i32 i;
        stpr $17:f64 = ld:f64:32 x;
        stpr $18:i32 = 1:i32;
        stpr $21:f64 = ld:f64:16 x;
        label "_GR__$L1";
        phi $19:i32 = (1:i32,"_GR__$L3"),($20:i32,"_GR__$L4");
        stpr $1:i32 = $19:i32;
        stpr $2:i32 = $16:i32;
        falsebr (
            le:bool 
                $19:i32, 
                $16:i32), "_GR__$L2";
        label "_GR__$L4";
        stpr $3:*<80> = lda x;
        stpr $4:u32 = 32:u32;
        stpr $5:*<8> = 
            lda:32 x;
        stpr $6:f64 = 
            $17:f64;
        stpr $7:f64 = 
            mul:f64 
                $17:f64, 0.400000:f64 ;
        stpr $8:*<80> = 
            lda x;
        stpr $9:u32 = 16:u32;
        stpr $22:f64 = 
            $7:f64;
        stpr $10:i32 = 
            $19:i32;
        stpr $11:i32 = 
            add:i32 
                $19:i32, 1:i32;
        stpr $20:i32 = 
            $11:i32;
        goto "_GR__$L1";
        label "_GR__$L2";
        return ;
    };
}
