region program x () {
    var swap:i8:(func,align(4));
    region func swap (undefined,
                      var a:*<1>:(align(4)), var b:*<1>:(align(4)),
                      var width:i32:(align(4))) {
        var temp:i8:(align(4));
        stpr $1:i32 = ld:i32 width;
        st:i32 width = sub:i32 ld:i32 width, 0x1:i32;
        while (ne $1:i32, 0x0:i32) {
            st:i8 temp = ild:i8 ld:*<1> a;
            stpr $2:*<1> = ld:*<1> a;
            ist:i8 = $2:*<1>,  ild:i8 ld:*<1> b;
            st:*<1> a = add:*<1> ld:*<1> a, 1:u32;
            stpr $3:*<1> = ld:*<1> b;
            ist:i8 = $3:*<1>, ld:i8 temp;
            st:*<1> b = add:*<1> ld:*<1> b, 1:u32;
            stpr $1:i32 = ld:i32 width;
            st:i32 width = sub:i32 ld:i32 width, 0x1:i32;
        };
        return;
    };
}
