region program ".program" () {
    var g:mc<400>:(array,align(4));
    var itrans_sp_chroma:any:(func,align(4));
    region func itrans_sp_chroma () {
        var i:i32:(align(4));
        var j:i32:(align(4));

        label "_GR__$L3";
        stpr $6:i32 = ld:i32 j;

        label "_GR__$L1";
        phi $8:i32 = (0:i32,"_GR__$L3"),($10:i32,"_GR__$L4");
        falsebr (lt $8:i32, 8:i32), "_GR__$L2";

        label "_GR__$L4";
        stpr $3:u32 = mul:u32 $8:i32, 10:u32;
        stpr $4:u32 = add:u32 $6:i32, $3:u32;
        stpr $5:u32 = mul:u32 $4:u32, 4:u32;
        ist:i32 = add:*<4> lda g, $5:u32,0:i32;
        stpr $10:i32 = add:i32 $8:i32, 1:i32;
        goto "_GR__$L1";

        label "_GR__$L2";
        return ;
    };
}
