region program "program" ()
{
    var foo:any:(func,align(4));
    region func foo (undefined,var a:*<1024>:(align(4)))
    {
        var i:i32:(align(4));
        var j:i32:(align(4));
        stpr $6:i32 = ld j;
        stpr $7:*<1024> = ld:*<1024> a;
        stpr $13:i32 = 0;
        label "$L1";
        stpr $9:i32 = $13;
        falsebr (lt $9, 16), "$L2";
        stpr $3:u32 = mul $9, 16;
        stpr $4:u32 = add $6, $3;
        stpr $5:u32 = mul $4, 4;
        stpr $12:*<4> = add:*<4> $7:*<1024>, $5:u32;
        ist:i32 = $12:*<4>,0;
        stpr $11:i32 = add $9, 1;
        stpr $13 = $11;
        goto "$L1";
        label "$L2";
        return;
    };
}
