  region program ".program" () {
      var x:i32:(align(4));
      var main:any:(func,align(4));
      var _const_string_1:str:(align(4));
      region func main () {
          var a:i32:(align(4));
          var b:i32:(align(4));
          var p:*<4>:(align(4));
          var i:i32:(align(4));
          var c:i32:(align(4));
          st:i32 i = 10:i32;
          st:i32 x = 4:i32;
          falsebr (
              ne:bool 10:i32, 0:i32), "_GR__$L4";
          st:*<4> p = 
              lda a;
          goto "_GR__$L5";
          label "_GR__$L4";
          st:*<4> p = 
              lda b;
          label "_GR__$L5";
          ist:i32 = 
              ld:*<4> p,10:i32;
          st:i32 c = 10:i32;
          st:i32 a = 5:i32;
          st:i32 b = 4:i32;
          ist:i32 = 
              ld:*<4> p,20:i32;
          return ld:i32 a;
      };
  }
