region program ".program" () {
    var g:i32:(align(4));
    var scalar:any:(func,align(4));
    var "#DedicatedStringVar":str:(unallocable,align(4));
    region func scalar (undefined,var i:i32:(align(4)),var j:i32:(align(4)),var a:*<8>:(restrict,align(4)),var b:*<8>:(restrict,align(4)),var c:*<8>:(restrict,align(4)),var n:i32:(align(4)),var m:i32:(align(4)),var o:i32:(align(4))) {
        var w:i32:(align(4));
        var u:i32:(align(4));
        var k:i32:(align(4));
        var t1:i32:(align(4));
        var t2:i32:(align(4));
        var t3:i32:(align(4));
        var t4:i32:(align(4));
        var DummyGlobalVarPointedByVAR65:mc<0>:(unallocable);
        var DummyGlobalVarPointedByVAR66:mc<0>:(unallocable);
        st:i32 k = 0:i32;
        st:i32 k = 0:i32;

        //
        label "_GR__$L4";
        falsebr (
            lt:bool
                ld:i32 k,
                ld:i32 o), "_GR__$L2";
        st:i32 t1 =
            mul:i32
                ld:i32 i,
                ld:i32 n;
        st:i32 t2 =
            mul:i32
                ld:i32 j,
                ld:i32 m;
        st:i32 t3 =
            add:i32
                ld:i32 t1,
                ld:i32 k;
        st:i32 t4 =
            add:i32
                ld:i32 t2,
                ld:i32 k;
        stpr $5:i32 =
            mul:i32
                ld:i32 t3, 8:i32;
        stpr $6:*<8> =
            add:*<8>
                ld:*<8> a,
                $5:i32;
        stpr $7:i32 =
            mul:i32
                ld:i32 t4, 8:i32;
        stpr $8:*<8> =
            add:*<8>
                ld:*<8> b,
                $7:i32;
        ist:f64 =
            $6:*<8>,
            ild:f64
                $8:*<8>;
        st:i32 k =
            add:i32
                ld:i32 k, 1:i32;
        goto "_GR__$L4";
        label "_GR__$L2";
        return ;
    };
}
