region program x() {
    var exitflag:u32:(align(4));
    var s:mc<4>:(array,align(4),byte(0x0,0x0,0x0,0x0));
    region func foo (var func_retval0:u32:(align(4))) {
        stpr $19:*<1> = 
            lda s;
        stpr $1:u16 = 
            ild:u16 
                $19:*<1>;
        stpr $23:u64 = 
            add:u64 
                $28:u64, 64527:u64;
        stpr $2:u16 = 
            band:u16 
                $1:u16, 
                $23:u16;
        stpr $24:u64 = 
            add:u64 
                $28:u64, 496:u64;
        stpr $3:u16 = 
            bor:u16 
                $2:u16, 
                $24:u16;
        ist:u16 = 
            $19:*<1>,
            $3:u16;
        stpr $4:u16 = 
            ild:u16 
                $19:*<1>;
        stpr $5:u16 = 
            lsr:u16 
                $4:u16, 4:u16;
        stpr $6:u16 = 
            band:u16 
                $5:u16, 15:u16;
        stpr $25:u64 = 
            add:u64 
                $28:u64, 65520:u64;
        stpr $7:u16 = 
            band:u16 
                $4:u16, 
                $25:u16;
        stpr $8:u16 = 
            bor:u16 
                $7:u16, 
                $6:u16;
        ist:u16 = 
            $19:*<1>,
            $8:u16;
        stpr $9:u16 = 
            ild:u16 
                $19:*<1>;
        stpr $10:u16 = 
            band:u16 
                $9:u16, 15:u16;
        stpr $11:u16 = 
            lsl:u16 
                $10:u16, 4:u16;
        stpr $26:u64 = 
            add:u64 
                $28:u64, 64527:u64;
        stpr $12:u16 = 
            band:u16 
                $9:u16, 
                $26:u16;
        stpr $13:u16 = 
            bor:u16 
                $12:u16, 
                $11:u16;
        ist:u16 = 
            $19:*<1>,
            $13:u16;
        stpr $14:u16 = 
            ild:u16 
                $19:*<1>;
        stpr $15:u16 = 
            lsr:u16 
                $14:u16, 4:u16;
        stpr $16:u16 = 
            band:u16 
                $15:u16, 63:u16;
        stpr $29:i64 = 
            cvt:i64 
                $16:i16;
        stpr $27:bool = 
            eq:bool 
                $29:i64, 15:i64;
        truebr (
            ne:bool 
                $27:bool, 0:bool), label_BB0_2;
        label label_BB0_1;
        stpr $20:*<1> = 
            lda exitflag;
        stpr $17:u64 = 
            add:u64 
                $28:u64, 1:u64;
        ist:u32 = 
            $20:*<1>,
            $17:u32;
        label label_BB0_2;
        stpr $18:u64 = 
            add:u64 
                $28:u64, 0:u64;
        st:u32 func_retval0 = 
            $18:u32;
        return ;
    };
}
