ARM_OBJS +=\
../arm/armasmprinter.o\
../arm/arm_cg.o\
../arm/arm_sim.o\
../arm/arm_cgmgr.o\
../arm/arm.o\
../arm/armir2or.o\
../arm/arm_lis.o\
../arm/arm_lra.o\
../arm/arm_or.o\
../arm/arm_passmgr.o\
../arm/arm_ramgr.o\
../arm/arm_region.o\
../arm/arm_region_mgr.o\
../arm/arm_scalar_opt.o\
../arm/arm_sr.o\
../arm/arm_var.o
