region program program() {
    var a:u64:(align(4));
    var b:u64:(align(4));
    var c:i32:(align(4));
    var d:i32:(align(4));
    var x:i32:(align(4));
    var y:i32:(align(4));
    var z:i32:(align(4));
    var w:i32:(align(4));
    var u:i32:(align(4));
    var main:*<4>:(func,align(4));
    var foo:any:(func, align(4));
    var bar:any:(func, align(4));
    region func main() {
        stpr $2 = lda c;
        stpr $3 = lda d;
        st x = $2;
        st y = $3;
        truebr (gt ld c, ld d), L1;

        call $5 = foo(); 

        stpr $2 = ld a;
        st w = $2;
        call bar($2);

        label L1;
        st u = $2;
        return $2;
    };
}
