region program ".program" () {
    var printf:any:(func,decl,align(4));
    var A:i32:(align(4));
    var B:i32:(align(4));
    var C:i32:(align(4));
    var foo:any:(func,align(4));
    var main:any:(func,align(4));
    var _const_string_1:str:(string("\n >>%d,%d<< \n"),align(4));
    var _const_string_2:str:(string("\n succ \n"),align(4));
    var _const_string_3:str:(string("\n fail \n"),align(4));
    region func foo (undefined,var i:i32:(align(4))) {
        falsebr (gt:bool ld:i32 A, ld:i32 B), "_GR__$L1";

        label L_LEFT;
        stpr $1:i32 = add:i32 ld:i32 A, ld:i32 B;
        st:i32 C = add:i32 $1:i32, 5:i32;
        goto "_GR__$L2";

        label "_GR__$L1";
        label L_RIGHT;
        stpr $2:i32 = sub:i32 ld:i32 A, ld:i32 B;
        st:i32 C = sub:i32 $2:i32, 5:i32;

        label "_GR__$L2";
        phi $4:u32 = ($1:u32, L_LEFT), ($2:u32, L_RIGHT);
        return add ld:i32 C, $4;
    };
    region func main () {
        var w:i32:(align(4));
        st:i32 A = 2:i32;
        st:i32 B = 1:i32;
        st:i32 C = 100:i32;
        call $1:i32 = foo(1:i32);
        st:i32 w = $1:i32;
        call $2:i32 = printf(lda _const_string_1, ld:i32 C, ld:i32 w);
        if (ne:bool ld:i32 C, 8:i32) {
            call printf(lda _const_string_3);
            return -1:i32;
        };
        call printf(lda _const_string_2);
        return 0:i32;
    };
}
