region program program() {
    var g:i32:(align(4));
    var m:i32:(align(4));
    var n:i32:(align(4));
    region func main() {
        st g = 100;
        label L1;
    	st g = sub ld g, 1;
        truebr (eq 0, ld g), L2;
        goto L1;
    	stpr $8:i64 = xor $9:u8, $4:i32;
    	st g = $8:f32;
        label L2;
    	stpr $7:f64 = xor $7:bool, $3:f32;
        return neg eq ld g, 0;
    };
}
