region program @".program" () {
    var printf:i8:(func_decl,readonly,align(4));
    var main:i32:(func_decl,align(4));
    var _const_string_1:str:(align(4),string("
success
"));
    var _const_string_2:str:(align(4),string("
failed!
"));
    region func main () {
        var a:i32:(align(4));
        var b:i32:(align(4));
        st:i32 a = 0xffffFFFFF:i32;
        stpr $1:i32 = ld:i32 a;
        setelem $1:i64 = ld:i32 a/*base*/, 0xee:i8/*value*/, 32/*offset*/;
        //getelem $2:i8 = $1/*base*/, 16/*offset*/;
        st:i32 b = $1:i32;
        //if (ne ld:i32 b, 0xffff6400:i32) {
        //    call $1:i8 = printf(lda _const_string_1);
        //    return $3;
    	//} else {
        //    call $1:i8 = printf(lda _const_string_2);
        //}
        return 0;
    };
}
