
//====---- Dump region '.program' ----====
region program @".program" () {

    var printf:i8:(func_decl,readonly,align(4));
    var main:i32:(func_decl,align(4));
    var _const_string_1:str:(align(4),string("
success
"));
    var _const_string_2:str:(align(4),string("
failed!
"));
    //====---- Dump region 'main' ----====
    region func main () {

        var a:i32:(align(4));
        var b:i32:(align(4));
        st:i32 a = 0xffffffffffffffff:i32;
        stpr $1:i32 = 
            ld:i32 a;
        setelem $1:i64 = 
            ld:i32 a,0xffffffffffffffee:i8,0x20:i32;
        st:i32 b = 
            $1:i32;
        return 0x0:i32;
    };
}